name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update 
      run: sudo apt-get update
    
    - name: Install Dep
      run: sudo apt-get -y install tar xz-utils
    
    - name: List Files
      run: ls -l
    
    - name: mkdir
      run: mkdir tuts
    
    - name: move
      run: mv -fv * tuts/ 
    
    - name: tar
      run: tar -Jcvf learnopencv.tar.xz tuts/

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: OS
        path: learnopencv.tar.xz
